### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by veyselpehlivan** [proleap/proleap-cobol#1]
When I try to do `$ mvn clean install`, I got the following.
```
401 Unauthorized
{"errors":[{"code":"UNAUTHORIZED","message":"You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication"}]}
```

**Comment by uwol** [comment]
Hi @veyselpehlivan ,

thanks for the info. You are right, the Maven pom tries to push an image of the build to Google Cloud in the last step. I made this step optional in 86631fb975322a385ba50d09e7c89b69ec4c8f3a. Please update from GitHub, should work now.

Best
Ulrich
