### ISSUE TITLE
Missing artifact io.github.uwol:proleap-cobol-parser:jar:4.0.0

### ISSUE THREAD

**Issue by RajSakpal** [proleap/proleap-cobol#2]
Hi,
Before I begin with my issue , I would like to mention that I am fairly new to the Java space. 
I've been following the steps you provided to simulate the Cobol to Java functionality similar to https://www.proleap.io/.
When I clone this project, I get the Missing artifact io.github.uwol:proleap-cobol-parser:jar:4.0.0 in the in all packages except 'proleap-cobol-api'. Also the test cases for the proleap-cobol-parser fail when I try to clean install.

If there is any document you could provide detailing the steps I could follow to achieve my objective would greatly help.

**Comment by uwol** [comment]
Hi @RajSakpal ,

you need to import the project `proleap-cobol-parser` into Eclipse. This is described in the last step of chapter `Build dependency proleap-cobol-parser` of the README.md

After importing the project into Eclipse, the error messages should disappear.

Best
Ulrich
