### ISSUE TITLE
Java executable gives the following error while trying to hit endpoints for transformation, analyze etc.

### ISSUE THREAD

**Issue by RajSakpal** [proleap/proleap-cobol#3]
io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.proleap.cobol.service.transform.cobol.CobolTextTransformService] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).

**Comment by uwol** [comment]
Hi @RajSakpal ,

in that case Annotation Processing is not configured properly in Eclipse. Open Eclipse > Preferences > Maven > Annotation Processing and select "Automatically configure JDT APT", so that dependency injection framework [Micronaut](https://micronaut.io/) automatically processes all @Inject annotations.

Then please clean and rebuild the project in Eclipse.

Best
Ulrich

**Comment by RajSakpal** [comment]
I'm not having this issue while running the project in Eclipse.
Only when I create Runnable Jar from the project, then run it on the terminal using `java -jar filename.jar` and then try to hit http://localhost:4567/v1/cobol/transform/text for transforming Cobol code.

**Comment by uwol** [comment]
Maven creates a separate JAR file for each Maven module / project. Thus, the JAR you are trying to start does not contain the code from the other maven projects such as proleap-cobol-transform, but only from the proleap-cobol-app project. 

Solutions:

- We normally start the server in Eclipse, or deploy to production based on JIB Maven Plugin, which is configured in pom.xml of proleap-cobol-app.
- You could add all the other JAR files from the target folders as libs to the `java -jar filename.jar` call. A little bit cumbersome.
- Add something like [maven-assembly-plugin](https://stackoverflow.com/questions/574594/how-can-i-create-an-executable-runnable-jar-with-dependencies-using-maven) to proleap-cobol-app to build a standalone JAR.

Best
Ulrich

**Comment by RajSakpal** [comment]
Thank you for the solutions, I was able to create a docker image using the JIB Maven Plugin you suggested.
